export default async(parent,{skip=0,take=10,teacherId},{prisma,req})=>{
    return await prisma.appointment.findMany({
        skip,take,
        where:{
            payment:{
                is:null
            },teacherId,
            stateKey:"accepted"

        },
        orderBy:{
            createdAt:"desc"
        },
        include:{
            student:true,
            course:{
                select:{
                    education_level:{
                        select:{
                            lookUp:true,
                            type:{
                                select:{
                                    name:true
                                }
                            }
                        }
                    }
                }
            },
            teacher:{
                select:{
                    id:true,
                    userInfo:{
                        select:{
                            image_URL:true,
                            address:true
                        }
                    },
                    full_name:true,
                    email:true,
                    phone_number:true
                }
            }
        }
    })
}